name: tests

on:
  push:
    branches:
      - v1
      - v2
      - v3
      - v4
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: [8.2, 8.3, 8.4, 8.5]
        laravel: ['11.*', '12.*', '13.*']
        stability: [prefer-lowest, prefer-stable]
        include:
          - laravel: 11.*
            testbench: 9.*
            eol: true
          - laravel: 12.*
            testbench: 10.*
          - laravel: 13.*
            testbench: 11.*
        exclude:
          - laravel: 13.*
            php: 8.2

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, bcmath, intl, exif, iconv, fileinfo, sqlite, pdo_sqlite
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Allow EOL framework installs
        if: matrix.eol
        run: composer config policy.advisories.block false

      - name: Install dependencies
        run: |
          composer update --${{ matrix.stability }} --with=laravel/framework:${{ matrix.laravel }} --with=orchestra/testbench-core:${{ matrix.testbench }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/pest
